{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "showroom-cpu-small.yaml",
    "showroom-l40s-1.yaml",
    "showroom-l40s-4.yaml",
    "showroom-platform-admins.yaml",
    "showroom-data-scientists.yaml",
    "showroom-visitors.yaml",
    "model-access.yaml",
    "showroom-test-drive.yaml",
    "showroom-standard.yaml"
  ]
}
