FROM registry.access.redhat.com/ubi9/python-312@sha256:ff373f4b42b662e99954adea770ca87b4ea963186cc752174ccb94aa08fa702d
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 HOME=/tmp
USER 0
WORKDIR /opt/app-root/src
COPY requirements.txt .
RUN pip install --no-cache-dir --requirement requirements.txt && \
    chgrp -R 0 /opt/app-root && chmod -R g=u /opt/app-root
COPY --chown=1001:0 business.py server.py ./
USER 1001
EXPOSE 8000
CMD ["python", "server.py"]
