{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "namespace.yaml",
    "model.yaml",
    "maas-ref.yaml",
    "access.yaml",
    "subscription.yaml"
  ]
}
