apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-showroom
resources:
  - server.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: aurora-tools-lifecycle-data
    files:
      - products.json
      - forecasts.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: rhoai-showroom
