apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../components/foundation
- ../../components/storage
- ../../components/mlflow
- ../../components/evaluation
- ../../components/mcp
- ../../components/guardrails/mcp-integration
- ../../components/science
- ../../components/experience
- ../../profiles/existing-cluster
- ../../components/mcp/public
- ../../components/mcp/lifecycle-isolation
- ../../components/mcp/lifecycle
- ../../components/models/registry
