apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-showroom-sandbox
resources:
- prerequisites.yaml
- access.yaml
configMapGenerator:
- name: showroom-openshell-access
  files:
  - authz.py
  - envoy.yaml
generatorOptions:
  disableNameSuffixHash: true
