apiVersion: v1
kind: Namespace
metadata:
  name: agent-sandbox-system
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: agent-sandbox
  namespace: agent-sandbox-system
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: agent-sandbox-operator
  namespace: agent-sandbox-system
spec:
  channel: preview-0.9
  installPlanApproval: Manual
  name: agent-sandbox-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: agent-sandbox-operator.v0.9.0
