apiVersion: v1
kind: ConfigMap
metadata:
  name: showroom-service-ca
  namespace: ai-showroom
  annotations:
    service.beta.openshift.io/inject-cabundle: 'true'
data: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aurora-science-config
  namespace: ai-showroom
data:
  AWS_S3_ENDPOINT: http://showroom-s3.ai-showroom.svc.cluster.local:8333
  MLFLOW_S3_ENDPOINT_URL: http://showroom-s3.ai-showroom.svc.cluster.local:8333
  AWS_DEFAULT_REGION: us-east-1
  AURORA_MLFLOW_TRACKING_URI: https://mlflow.redhat-ods-applications.svc:8443/mlflow
  MLFLOW_TRACKING_URI: https://mlflow.redhat-ods-applications.svc:8443/mlflow
  MLFLOW_TRACKING_SERVER_CERT_PATH: /etc/service-ca/service-ca.crt
  MLFLOW_WORKSPACE: ai-showroom
  MCP_URL: http://showroom-mcp-istio.ai-showroom.svc:8080/mcp
