apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: showroom-pipelines
  namespace: ai-showroom
spec:
  apiServer:
    cacheEnabled: false
    managedPipelines:
      image: registry.redhat.io/rhoai/odh-pipelines-components-rhel9@sha256:509cc5943bb396a888c3e2ee66b20d868b60536e4f2e52bc06a7e85cdf70199e
  mlflow:
    integrationMode: AUTODETECT
    injectUserEnvVars: true
  objectStorage:
    externalStorage:
      host: showroom-s3.ai-showroom.svc.cluster.local
      port: '8333'
      scheme: http
      bucket: aurora-artifacts
      region: us-east-1
      s3CredentialsSecret:
        secretName: showroom-s3-credentials
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
