FROM registry.access.redhat.com/ubi9/python-312@sha256:ff373f4b42b662e99954adea770ca87b4ea963186cc752174ccb94aa08fa702d
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 HOME=/tmp
WORKDIR /opt/app-root/src
COPY --chown=1001:0 server.py ./
USER 1001
EXPOSE 8443
CMD ["python", "server.py"]
