apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: redhataigranite-31-8b-instruct
  namespace: ahead
spec:
  modelRef:
    kind: LLMInferenceService
    name: redhataigranite-31-8b-instruct
  tenantRef: ahead
---
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSAuthPolicy
metadata:
  name: ahead-granite-presenter-access
  namespace: ai-tenant-ahead
spec:
  modelRefs:
  - name: redhataigranite-31-8b-instruct
    namespace: ahead
  subjects:
    users:
    - aiadmin
---
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSSubscription
metadata:
  name: ahead-granite-presenter
  namespace: ai-tenant-ahead
spec:
  modelRefs:
  - name: redhataigranite-31-8b-instruct
    namespace: ahead
    tokenRateLimits:
    - limit: 20000
      window: 1m
  owner:
    users:
    - aiadmin
  priority: 60
