apiVersion: v1
kind: ConfigMap
metadata:
  name: showroom-mcp-options
data:
  service: "spec:\n  type: ClusterIP\n"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: showroom-mcp
  labels:
    app.kubernetes.io/part-of: rhoai-showroom
spec:
  gatewayClassName: openshift-default
  infrastructure:
    parametersRef:
      group: ''
      kind: ConfigMap
      name: showroom-mcp-options
  listeners:
  - name: mcp
    port: 8080
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
  - name: mcps
    port: 8081
    protocol: HTTP
    hostname: '*.mcp.internal'
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: mcp.kuadrant.io/v1alpha1
kind: MCPGatewayExtension
metadata:
  name: showroom-mcp
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: showroom-mcp
    namespace: ai-showroom
    sectionName: mcp
  publicHost: showroom-mcp-istio.ai-showroom.svc.cluster.local:8080
  privateHost: http://showroom-mcp-istio.ai-showroom.svc.cluster.local:8080
  httpRouteManagement: Disabled
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: showroom-mcp-entry
spec:
  parentRefs:
  - name: showroom-mcp
    sectionName: mcp
    group: gateway.networking.k8s.io
    kind: Gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /mcp
    backendRefs:
    - name: mcp-gateway
      port: 8080
      group: ''
      kind: Service
      weight: 1
---
apiVersion: v1
kind: Service
metadata:
  name: showroom-mcp-istio
spec:
  type: ClusterIP
  selector:
    gateway.networking.k8s.io/gateway-name: showroom-mcp
  ports:
  - name: mcp
    port: 8080
    targetPort: 8080
  - name: mcps
    port: 8081
    targetPort: 8081
