{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "../qwen-4b",
    "gateway.yaml"
  ],
  "patches": [
    {
      "path": "private-route-patch.yaml"
    },
    {
      "path": "disable-maas-0.yaml"
    },
    {
      "path": "disable-maas-1.yaml"
    },
    {
      "path": "disable-maas-2.yaml"
    }
  ]
}
